#!/bin/bash

# 환경 변수 설정
USERNAME=$(whoami)
SERVICE_NAME="Palworld"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
VERSION="0.1.2"
INIT_FLAG_FILE="${HOME%/}/.script_init_done"
GITHUB_URL="https://raw.githubusercontent.com/kwakdolseok/maruta/main/palworld"

# 메시지 출력 함수
print_message() {
    echo -e "[\033[1;34m마루타 구동기\033[0m] $1"
}

# 서비스 파일 생성 함수
create_service_file() {
    [ -f "$SERVICE_FILE" ] && return

    sudo tee "$SERVICE_FILE" >/dev/null <<EOF
[Unit]
Description=Palworld Service
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=$USERNAME
Group=$USERNAME
WorkingDirectory=${HOME%/}/Steam/steamapps/common/PalServer
ExecStart=${HOME%/}/Steam/steamapps/common/PalServer/PalServer.sh -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

    sudo systemctl daemon-reload
    sudo systemctl enable $SERVICE_NAME
    print_message "$SERVICE_NAME 시스템에 구동기 등록이 완료되었습니다."
}

read_palworld_settings() {
    local ini_file="$HOME/Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini"

    # 파일 존재 여부 확인
    if [ ! -f "$ini_file" ]; then
        print_message "Error: $ini_file 파일을 찾을 수 없습니다."
        return 1
    fi

    # RCONEnabled 값 확인 및 필요한 경우 True로 변경
    if grep -q 'RCONEnabled=False' "$ini_file"; then
        sed -i 's/RCONEnabled=False/RCONEnabled=True/' "$ini_file"
        print_message "RCONEnabled 설정이 False에서 True로 변경되었습니다."
    else
        print_message "RCONEnabled 설정은 이미 True입니다."
    fi

    # AdminPassword 값 추출
    local admin_password=$(awk '/OptionSettings=/ {match($0, /AdminPassword="([^"]*)"/, arr); print arr[1]}' "$ini_file")
    
    # RCONPort 값 추출
    local rcon_port=$(awk '/OptionSettings=/ {match($0, /RCONPort=([0-9]+)/, arr); print arr[1]}' "$ini_file")

    # 추출된 값 출력
    print_message "AdminPassword: $admin_password"
    print_message "RCONPort: $rcon_port"
}


execute_rcon_command() {
    local command=$1  # 실행할 RCON 명령

    # read_palworld_settings 함수로부터 설정 값 추출
    local settings=$(read_palworld_settings)
    local admin_password=$(echo "$settings" | grep 'AdminPassword' | cut -d' ' -f2)
    local rcon_port=$(echo "$settings" | grep 'RCONPort' | cut -d' ' -f2)

    # RCONEnabled 값 확인 (옵션)
    local rcon_enabled=$(echo "$settings" | grep 'RCONEnabled' | cut -d' ' -f2)
    if [[ "$rcon_enabled" != "True" ]]; then
        print_message "RCONEnabled 설정이 True로 설정되지 않았습니다."
        return 1
    fi

    # RCON 명령 실행
    if [[ -n "$admin_password" && -n "$rcon_port" ]]; then
        print_message "RCON 명령 실행: $command"
        arrcon -s localhost -p "$rcon_port" -P "$admin_password" "$command"
    else
        print_message "AdminPassword 또는 RCONPort가 설정되지 않았습니다."
    fi
}
# 서비스 시작 함수
start_service() {
    if [ "$(systemctl is-active $SERVICE_NAME)" = "active" ]; then
        print_message "현재 Palworld Server 서버가 이미 실행 중입니다."
    else
        sudo systemctl start $SERVICE_NAME
        print_message "Palworld Server 서비스를 시작합니다."
    fi
}

# 서비스 중지 함수
stop_service() {
    if systemctl is-active --quiet $SERVICE_NAME; then
        print_message "서버에 save 명령을 보냅니다."
        execute_rcon_command "save"
        sleep 10
        sudo systemctl stop $SERVICE_NAME
        print_message "서버를 중지합니다..."
        sleep 2  # 잠시 대기
        if systemctl is-active --quiet $SERVICE_NAME; then
            print_message "서버가 정상적으로 종료되지 않았습니다."
        else
            print_message "서버가 정상적으로 종료되었습니다."
        fi
    else
        print_message "서버는 이미 중지된 상태입니다."
    fi
}

# 서비스 업데이트 함수
update_service() {
    stop_service
    print_message "Palworld 서버 업데이트를 시작합니다..."
    update_result=$(steamcmd +login anonymous +app_update 2394010 validate +quit 2>&1)
    
    if echo "$update_result" | grep -q "Success! App '2394010' fully installed."; then
        print_message "업데이트 완료! 게임 서버를 다시 시작합니다."
        start_service
    elif echo "$update_result" | grep -q "Error"; then
        print_message "업데이트 중 오류가 발생했습니다. 상세 정보:"
        echo "$update_result"
    else
        print_message "업데이트 상태를 확인할 수 없습니다. 상세 로그를 확인하세요:"
        echo "$update_result"
    fi
}


# 스크립트 업데이트 확인 및 실행
check_and_update_script() {
    # 첫 번째 인자로 'noupdate'를 받으면 업데이트 검사를 건너뜁니다.
    if [ "$1" = "noupdate" ]; then
        return
    fi

    local remote_version=$(wget -qO- https://raw.githubusercontent.com/kwakdolseok/maruta/main/palworld | grep '^VERSION=' | head -1 | cut -d '"' -f 2)

    if [ "$VERSION" != "$remote_version" ]; then
        print_message "새 버전 $remote_version 발견. 업데이트를 진행하시겠습니까? (yes/y 또는 no/n)"
        read -r user_input
        case $user_input in
            yes|y|YES|Y)
                print_message "스크립트를 업데이트하고 있습니다..."
                wget -q -O ~/palworld https://raw.githubusercontent.com/kwakdolseok/maruta/main/palworld
                chmod +x ~/palworld
                # 업데이트 후 스크립트를 실행할 때 'noupdate' 인자를 전달합니다.
                exec ~/palworld noupdate
                ;;
            no|n|NO|N)
                print_message "업데이트를 취소했습니다."
                ;;
            *)
                print_message "잘못된 입력입니다. 업데이트를 취소합니다."
                ;;
        esac
    fi
}

# 업데이트 체크 함수를 호출합니다.
check_and_update_script

# 초기 설정 함수
initialize_script() {
    create_service_file
    touch "$INIT_FLAG_FILE"
}

# 초기 설정 확인 및 실행
[ ! -f "$INIT_FLAG_FILE" ] && initialize_script


control_service() {
    case $1 in
        start|START|st|ST|시작)
            start_service
            ;;
        stop|STOP|sp|SP|정지)
            stop_service
            ;;
        update|UPDATE|up|UP|업데이트)
            update_service
            ;;
        *)
            echo "사용 가능한 명령어: start, stop, update"
            ;;
    esac
}

# 명령어 인자에 따른 서비스 제어
control_service "$1"
